name: Unit Tests

on:
  push:
    branches:
      - develop
      - production
  pull_request:

jobs:
  php-tests:
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
        wordpress: ["latest"]
        multisite: [true, false]
    uses: alleyinteractive/.github/.github/workflows/php-tests.yml@main
    with:
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wordpress }}
      multisite: ${{ matrix.multisite }}
